### ISSUE TITLE
使用该shortcut时候在翻译阶段报错

### ISSUE THREAD

**Issue by mivansaka** [BlackwinMin/shortcuts-actions-gallery#4]
你好，在使用该捷径时，翻译的时候会报错：ONGOING_SPEECH_TRANS-LATION_ERROR_DESCRIP-TION
确认权限已经给出，麻烦开发者排查了

**Comment by BlackwinMin** [comment]
请问“该捷径”是哪个？系统版本？不知道这些，我无法给出任何建议。

**Comment by mivansaka** [comment]
啊啊！对不起不好意思，我指的是Contacts Sort这个捷径，我的最新版本是iOS 17 beta，但是上个月在16.5也有复现。我今天调试了一下，应该是在循环下翻译频率过快报错了，我在翻译前加了2s的延时就能顺利跑完了

**Comment by BlackwinMin** [comment]
是的，这是 Shortcuts 翻译引擎的问题，自 iOS 15 或 iOS 16 开始，Apple 将 Microsoft 翻译引擎换成了自家的，就会出现这一问题，除了增加延迟，其余无解。
